### ISSUE TITLE
Hotkey Support

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#12]
- research: declarative approach? Existing solutions.

[Hotkeys documentation](https://github.com/Amplicode/amplicode-frontend/issues/1#issue-1009579580)

### Default jmix hotkeys

`@haulmont/jmix-front-generator` adds some default application hotkeys while generation:
- useDefaultTabHotkeys()
- useDefaultEditorHotkeys()
- useDefaultBrowserTableHotkeys()

## Test requirements

5 e2e tests

### QA Notes

Button for open list of available hotkeys is placed in the header. All of them should work correctly:
![79858906b70feb8d6ef47fb7ba79e19a.png](https://images.zenhubusercontent.com/60000500c28f518445606026/1c999c51-16e5-4361-8760-708b4bc6d676)

The list of available hotkeys looks like this:
![3397c355e079d13a5333f724d923251f.png](https://images.zenhubusercontent.com/60000500c28f518445606026/b66a8ce3-01af-4134-97c9-257c30dbfdf6)

**Comment by vyacheslav-pushkin** [comment]
Superseeded by https://github.com/Amplicode/amplicode-frontend/issues/1

**Comment by owlet1997** [comment]
Please add some fixes to the hotkeys description:
- Switch to **the** next tab
- Switch to **the** previous tab
- Open/close **the** help page
- Edit **the** entity
- Create **an** entity
- Delete **the** entity
- Save **the** entity

Also change the order for items:
1. Shortcuts Help
2. Tabs
3. Entity Editor
4. Entity List

**Comment by web-devel** [comment]
Also, I think using arrow keys for (main) tab switching is against accessibility best practices.
https://webaim.org/techniques/keyboard/

Let's pick another hotkey for tab switching.

**Comment by HegelPro** [comment]
@web-devel , I think `alt+arrow left` and `alt+arrow right` will be good. Chrome has those shortcuts for working with browser history:
![2ec4105726e90a0a236f0d3c5f1e1f69](https://user-images.githubusercontent.com/34520941/142638661-0061bc8d-1246-4bf9-8101-c2c37500a7ae.png)
Now browser native behavior breaks our tabs. I suggest redefining them.

**Comment by vyacheslav-pushkin** [comment]
Wouldn't that mean that our hotkeys will clash with Chrome hotkeys?:

**Comment by HegelPro** [comment]
@vyacheslav-pushkin , need to think.
but:
- `shift+arrow left` using for highlight text in inputs
- `ctrl+arrow left` using for move between words in inputs
- `alt+arrow left` using for switch browser history

**Comment by HegelPro** [comment]
We decided to use a pattern with the g key(go to somewhere):
`g+n` - go to the next tab
`g+p` - go to the previous tab
`g+e` - go to edit the entity
`g+c` - go to create an entity
