### ISSUE TITLE
CRUD component for composite PK entities

### ISSUE THREAD

**Issue by karandashovrz** [Haulmont/jmix-frontend#135]
Duplicate CUBA issue https://app.zenhub.com/workspaces/frontend-5e207f4452024f50534b5232/issues/cuba-platform/frontend/203

**Comment by lovtsovaik** [comment]
testing is blocked by https://github.com/Haulmont/jmix-core/issues/128 and https://github.com/Haulmont/jmix-core/issues/104

**Comment by lovtsovaik** [comment]
At the moment, the id attributes are not displayed on screens, therefore:
- Create - doesn't work
- Read - works without id attributes
- Update - works if you edit attributes not included in id
- Delete - works well
