### ISSUE TITLE
Exception with serialization entity with OffsetTime attribute

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-frontend#142]
Enviroment:
JMIX platfrom v.1.0.0-SNAPSHOT

it was checked via using frontend module
Steps:

1. Open [attached](https://github.com/Haulmont/jmix-frontend/files/6089984/access.zip) project
2. Run app
3. Open OffsetTime Management page
4. Create new instance -> Save it

AR:
there is an error
![image](https://user-images.githubusercontent.com/45730069/110105563-f9eab200-7dc1-11eb-9440-d4d23f1b4c8e.png)
and [exception](https://github.com/Haulmont/jmix-frontend/files/6089983/offsetexception.txt), instance has not been saved

**Comment by owlet1997** [comment]
[project with latest updates](https://app.zenhub.com/files/318761614/5d0bb1ec-df02-4f3a-ac40-f12e1af124cd/download)

**Comment by web-devel** [comment]
Current formates
{
  "localDate": "2021-02-24",
  "date": "2021-02-24",
  "localDateTime": "2021-02-24T15:15:15.053",
  "localTime": "15:15:15",
  "time": "15:15:15",
  "offsetDateTime": "2021-02-24T15:15:15.053+04:00",
  "offsetTime": "15:15:15+04:00"
}

**Comment by karandashovrz** [comment]
fixed in https://app.zenhub.com/workspaces/jmix-frontend-5fe0992a4308f20011f1c913/issues/haulmont/jmix-frontend/186

**Comment by HegelPro** [comment]
The server allows for localDateTime and offsetDateTime both formats:
- with milliseconds ('.SSS')
- without milliseconds ('.SSS')

If the server receives '.000' in a date it formats the date for a database into the date without milliseconds. 

The server sends a date in the formate which has been saved in a database(with or without '.SSS').
