### ISSUE TITLE
Entity creation wizard

### ISSUE THREAD

**Issue by web-devel** [Haulmont/jmix-frontend#150]
**Need to wait when the studio will support a param type for FormWizard.**

## Develop a demo component for form steps
- [x] Mobx store for form steps
- [x] Create ui-components for control form steps content
- [x] Create buttons for control form step
- [x] Create step status ui-component
- [x] Need to validate every step
- [x] Handle errors from the server
- [x] Add styles
- [x] Hide most part of implementation into packages

## Develop a generator for form steps
- [x] Deliver all needed properties into the template
- [x] Add Form Steps template
- [x] Need to know how the generator will get information about separate form by steps (???)

[Ant.design doc example](https://ant.design/components/form/#components-form-demo-form-context)

## QA:
template name: entity-form-wizard

template looks like:
![form-wizard](https://user-images.githubusercontent.com/34520941/124760461-d38c7d00-df41-11eb-9892-5c5e6fd8b79d.png)

The template should image errors correctly(like the entity-editor template):
- frontend errors(required fields)
- server errors(regexp)

**Comment by owlet1997** [comment]
**AR:**
fields are not displayed in the steps:
![image](https://user-images.githubusercontent.com/45730069/144846402-98f2becd-ee35-4313-a9d1-e990a7026eab.png)
![image](https://user-images.githubusercontent.com/45730069/144846424-413a3865-d2eb-4056-b8a9-e81fa7ed875e.png)
testing project [front.zip](https://github.com/Haulmont/jmix-frontend/files/7660660/front.zip)

**Comment by HegelPro** [comment]
Fixed
![81ddcb01b6dea03529cab5404f84f7e6.png](https://images.zenhubusercontent.com/60000500c28f518445606026/e4be1eec-d041-438d-814b-d0b2826bf687)

**Comment by owlet1997** [comment]
The client-side validation implemented [here](https://github.com/Haulmont/jmix-frontend/issues/744) should be added to the entity creation template
