### ISSUE TITLE
Entity list: table with bulk selection template

### ISSUE THREAD

**Issue by web-devel** [Haulmont/jmix-frontend#153]
**Need to wait when the studio will support new param types https://youtrack.haulmont.com/issue/JST-1215.**

## QA
template name: `entity-multi-selection-table`

the template looks like this:
![multi-select-table.png](https://images.zenhubusercontent.com/60000500c28f518445606026/e14a5647-3473-4d7b-92b9-de10811c0801)

Requirements:
- the template should image a list of entities correctly.
- selection of some entities should work correctly.
- the delete button should delete entities correctly.

**Comment by owlet1997** [comment]
**TC 1:**
1. Create entity with association 1-1 with itself 
2. Create Frontend component Multiselect table for this entity
3. Select attribute with the association in GraphQL constructor -> Finish editing

**AR:**
extra query was added to EntityList:
![image](https://user-images.githubusercontent.com/45730069/144836857-f5f4a4df-7116-4447-bfff-ce2cba4cf3ba.png)

**Comment by owlet1997** [comment]
generator 2.0.0-next.11
**TC 2:**

Select any entities in the Multiselect table -> Delete them

**AR:**
message for successful deleting is not defined:
![image](https://user-images.githubusercontent.com/45730069/144838080-6b179aaf-d442-4433-8608-931697350830.png)
