### ISSUE TITLE
Entities on calendar template

### ISSUE THREAD

**Issue by web-devel** [Haulmont/jmix-frontend#156]
Displays a set of entities as calendar events.

When creating a screen, user will choose:
- entity class
- attributes corresponding to:
  - event start (date/time)
  - event end (date/time)
  - title (string)
  - description (string)

## QA
**Need to wait when the studio will support new param types https://youtrack.haulmont.com/issue/JST-1215.**

**Comment by owlet1997** [comment]
Checked date formats:

- [ ] Date
- [ ] LocalDate
- [ ] LocalDateTime
- [ ] OffsetDateTime
