### ISSUE TITLE
JSX use-cases for IDE

### ISSUE THREAD

**Issue by web-devel** [Haulmont/jmix-frontend#188]

**Comment by karandashovrz** [comment]
Investigating was done on 1.0.SNAPSHOT692-202 build.
[Code examples with jsx use cases](https://app.zenhub.com/files/318761614/0dc4f22b-c299-4491-8e09-82822e419919/download)

The most popular JSX use cases, which you can see in real projects, includes next variations:

1. Conditional rendering:
JSX markup could be returned from logical blocks, for example:

- if block
- else if block
- else block
- && operator
- ternary expression
- switch block

In code examples you can see these use cases in _**use-cases\conditions\ConditionalComponents.tsx**_
If we look at React UI panel with components tree, we can see next:
- if, else if, else blocks always layout as if block
- switch block and cases don't layout on components tree. We can see only JSX which are inner case parts of switch
- Using ternary expression and && operator also don't layout on components tree. We can see only JSX elements.

![IDE screenshot conditional](https://images.zenhubusercontent.com/60000377f9c3e0334cc6b83d/beb41863-125a-4ce5-b925-718aad59a592)

2. Render methods:
JSX markup could be returned from functions. These functions called render methods or render functions.
You can call these functions to get JSX markup in components. Also, they could be called from inner of other JSX markup
In code examples you can see these use case in **_use-cases\render-function\RenderFunctionComponent.tsx_**
If we look at React UI panel with components tree, we can see next:
- If we call render method from inner of JSX element, it doesn't layout on components tree. We can see only parent JSX element.

![IDE screenshot render method](https://images.zenhubusercontent.com/60000377f9c3e0334cc6b83d/5f95915e-d0fb-4613-b0bc-7d7f3ca38fe9)

3. Variables and arrays with JSX.
You can assign JSX markup to some variable, and then, use it to get JSX markup in components. Variable with JSX could be used from inner of other JSX.
Also, you can put several JSX elements into array, and use this array to get several JSX elements in components.
In code examples you can see these use case in _**use-cases\jsx-element\JsxElementsComponent.tsx**_
If we look at React UI panel with components tree, we can see next:
- If we use variables with JSX or array with JSX from inner of JSX element, it doesn't layout on components tree. We can see only parent JSX element.

![IDE screenshot render method](https://images.zenhubusercontent.com/60000377f9c3e0334cc6b83d/32175baf-89ca-4a63-b055-b155117f0c3f)

4. Mapping
If you have array with some data, you can call map method on this array, and returned JSX markup. In fact, this is a special case of array with JSX. However, it is widely used
 in real projects to get JSX markup
In code examples you can see these use case in _**use-cases\mapping\ComponentWithMap.tsx**_
If we look at React UI panel with components tree, we can see next:
- If we use map method on array with data from inner of JSX element, we can see parent JSX element and JSX element,which was returned from map callback method, but only one.

![IDE screenshot render map](https://images.zenhubusercontent.com/60000377f9c3e0334cc6b83d/ad577daf-8bd5-4257-8937-b8552054ae69)

Corner cases:
1-4 points describe the most common and popular ways to use JSX markup. However, any combinations and their complex constructions give big variety of different JSX use cases that is difficult to predict.
