### ISSUE TITLE
Creating ClientSideDataCollectionStoreImpl obdject falls application in run-time

### ISSUE THREAD

**Issue by karandashovrz** [Haulmont/jmix-frontend#191]
![image.png](https://images.zenhubusercontent.com/60000377f9c3e0334cc6b83d/d3a871e1-7d1e-403f-9f1d-0eddd8cc1247)

**Comment by natfirst** [comment]
@karandashovrz please provide some test case to reproduce the problem

**Comment by karandashovrz** [comment]
@natfirst  Do you have accsess to our testing project scr-jmix? https://github.com/jmix-projects/scr-jmix
After you will generate front-moudle on this project and run it, you need to de next steps:
1) select Datatypes Management1 in left sidebar menu
2) click to create button
![image.png](https://images.zenhubusercontent.com/60000377f9c3e0334cc6b83d/752779a1-1c8d-43e6-8cde-1d542fa6b223)

Before this fix, application was crashed with error. Now, after create clicking, you will see create form.
