### ISSUE TITLE
Configurable selection type in DEV mode

### ISSUE THREAD

**Issue by web-devel** [Haulmont/jmix-frontend#212]
select element on hover
select element on click
selection disabled

**Comment by web-devel** [comment]
* select element on hover
* select element on click
* selection disabled

**Comment by karandashovrz** [comment]
For QA: in this ticket was implemented highlighting mode selection API. This functionality injected to inner mechanics of devmode front-end part. For testing, need to await compleating linked tasks in studio.

**Comment by lovtsovaik** [comment]
waiting for JST-1095
