### ISSUE TITLE
Components for conditional rendering

### ISSUE THREAD

**Issue by web-devel** [Haulmont/jmix-frontend#218]
Need to implement IF component for conditional rendering. This component is used for conditional rendering of components, which were returned from passed to onTrue render function. IF component is imported from **@haulmont/jmix-react-core** package.

Example:
```
const CustomComponent: React.FC = () => {
  return (
    <>
      <IF condition={true} onTrue = {() => (
        <div>
          any content
        </div>  
      )}/>
    </>
  )
}
```

**Comment by karandashovrz** [comment]
This component is used for conditional rendering of components 
 which were returned from passed to onTrue render function
 
Example:
```
const CustomComponent: React.FC = () => {
  return (
    <>
      <IF condition={true} onTrue = {() => (
        <div>
          any content
        </div>  
      )}/>
    </>
  )
}
```
