### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#22]
In this epic need to implement AppMenu component generation. File with AppMenu component is located on path projectFolder \ src \ app \ AppMenu.tsx. This file is generated with others files of project. It is updated on each component generation stage with adding new MenuItem component to inner of VerticalMenu. For correct routing working, each MenuItem component must have screenId property. Demo project

**Comment by karandashovrz** [comment]
In this epic was implemented AppMenu component generation. File with AppMenu component is located on path `projectFolder` \ src \ app \ AppMenu.tsx. This file is generated with others files of project. It is updated on each component generation stage with adding new MenuItem component to inner of VerticalMenu. For correct routing working, each MenuItem component must have screenId property.
