### ISSUE TITLE
Exclude generated docs from GitHub language detection

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#236]
Currently GitHub reports this repo as 81.8% HTML, apparently due to generated documentation:

![image](https://user-images.githubusercontent.com/8298981/115261617-d21e9600-a144-11eb-9ad0-a66430ac42ff.png)

We do have `.gitattributes` configured to ignore the docs but for some reason it doesn't work.

**Comment by web-devel** [comment]
Not sure why, but https://github.com/cuba-platform/frontend also has the same issue, so I guess it's some changes in github (linguist) mechanism

**Comment by web-devel** [comment]
Played with the [linguist](https://github.com/github/linguist) locally:
* clone linguist repo
* build docker image `docker build -t linguist .`
* navigate to the directory with our project, and run
```
docker run --rm -v $(pwd):$(pwd) -w $(pwd) -t linguist
```
Changing `.gitattributes` does not make any changes in the following breakdown:
```
83.12%  HTML
10.70%  TypeScript
4.35%   CSS
1.33%   JavaScript
0.34%   EJS
0.09%   Handlebars
0.05%   Less
0.02%   SCSS
0.01%   Shell
```

**Comment by web-devel** [comment]
It seems one need to commit `.gitattributes` before running linguist analysis
