### ISSUE TITLE
EntityList from EntityManagement frontend component has been generated with errors

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-frontend#266]
#### Enviroment:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2843-211
IntelliJ version: IntelliJ IDEA 2021.1 (Ultimate Edition)
frontend generator version 1.0.0-next.10

#### TC:
1. Create new project -> add Frontend module 
2. Create new Frontend component 'EntityManagement' -> choose User entity -> finish
3. Open UserList.tsx

#### AR:
there is an TypeScript error in `DataTable` component:
![image](https://user-images.githubusercontent.com/45730069/117264814-a8fc4600-ae64-11eb-9442-4ee2f686a798.png)
![image](https://user-images.githubusercontent.com/45730069/117264838-abf73680-ae64-11eb-80d3-0780f50ebb38.png)

after running app build will be failed:
![image](https://user-images.githubusercontent.com/45730069/117265296-2627bb00-ae65-11eb-8a9f-e96c8e5d7be2.png)

**Comment by web-devel** [comment]
I think it's time to replace the entity management-template

**Comment by lovtsovaik** [comment]
new problem with the list component is in another [ticket](https://youtrack.jmix.io/issue/JST-1315 )
