### ISSUE TITLE
Table looks weird when there is only one column

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#312]
Probably related to the way we hide selection column

![image](https://user-images.githubusercontent.com/8298981/119155884-b02a7300-ba64-11eb-97f1-5f9315f3b134.png)

**Comment by web-devel** [comment]
Probably related, quite strange column sizing by default
![image](https://user-images.githubusercontent.com/3295727/122684448-7a6cdb80-d216-11eb-8060-08e6f7fd8700.png)
