### ISSUE TITLE
Infinite spinner in List screen

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-frontend#327]
*Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2915-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Ultimate Edition)*

Open project [checkJSGQL.zip](https://github.com/Haulmont/jmix-frontend/files/6547200/checkJSGQL.zip)
Open Small List

AR: infinite spinner while request respons 200 
![image](https://user-images.githubusercontent.com/73226373/119672662-d62c8a80-be4b-11eb-928a-ee6581469cbe.png)
![image](https://user-images.githubusercontent.com/73226373/119672802-efcdd200-be4b-11eb-91fc-68ecadf55078.png)

Request URL: http://localhost:3000/graphql
Request Method: POST
Status Code: 200 OK

Nothing unusual has been done in this project. Just create an entity, attribute, frontend component. Create screens in Backoffice UI and add one instance for the entity.

**Comment by web-devel** [comment]
Due to the following bug https://github.com/Haulmont/jmix-security/issues/89
you need to add `    implementation 'io.jmix.rest:jmix-rest-starter'` in `build.gradle`
