### ISSUE TITLE
change behavior of caption property in MenuItem component

### ISSUE THREAD

**Issue by karandashovrz** [Haulmont/jmix-frontend#344]
In [this ticket](https://app.zenhub.com/workspaces/jmix-frontend-5fe0992a4308f20011f1c913/issues/haulmont/jmix-frontend/325) was added caption  property to MenuItem component. Need to chabge behavior of caption property with below points:

- make caption property as required property

- if title property is not set, caption property is used as tooltip caption, when menu is collapsed

**Comment by owlet1997** [comment]
Case:
set component caption using <Formatted message/>:
```
<MenuItem
            screenId={"NewComponent"}
            icon={<BarsOutlined />}
            caption={<FormattedMessage id={"router.NewComponent"} />}
            key={"2db42a0c-75c9-490d-a94c-8a2e09e06edf"}
          />
```

AR:
title has not been appearing

**Comment by karandashovrz** [comment]
@owlet1997 
Will be resolved in https://app.zenhub.com/workspaces/jmix-frontend-5fe0992a4308f20011f1c913/issues/haulmont/jmix-frontend/372
