### ISSUE TITLE
No login screen, immediately logged in as anonymous

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#353]
**To repoduce:**

1. Start dev server
2. Open `localhost:3000`

**ER:**

- Login screen is displayed.
- After logging in entity messages are requested from server.

**AR:**

- Immediately logged in as `anonymous`:
![image](https://user-images.githubusercontent.com/8298981/120482254-fddaa000-c3c1-11eb-89cf-de1fcbd382fb.png)

- After logging out and logging in as a valid user, entity messages are not requested. Page reload will trigger requesting the entity messages.

**Comment by web-devel** [comment]
Fixed in graphql
