### ISSUE TITLE
Missing filters in the table

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#354]
Filters are missing for certain attribute types, e.g. Big Decimal, integer:

![image](https://user-images.githubusercontent.com/8298981/120495805-1486f400-c3ce-11eb-8cff-82d2b5ce4af0.png)

**Comment by owlet1997** [comment]
Case:
- add Character field to entity
- generate Frontend entity management
- run app
- open entity browser

AR:
filter is absent
![image](https://user-images.githubusercontent.com/45730069/121363121-b31fd180-c947-11eb-8737-ab8bc6dab798.png)

**Comment by vyacheslav-pushkin** [comment]
related https://github.com/Haulmont/jmix-graphql/issues/134

**Comment by vyacheslav-pushkin** [comment]
@owlet1997 Merged a fix to master. Filter will appear but won't work due to above issue.
