### ISSUE TITLE
Permissions for menu items / screens

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-frontend#387]
In React client, it should be possible to configure different available menu structure for users with different roles.

We / users should understand that such permissions are checked only in UI and don't prevent anyone from calling public GraphQL / REST endpoints.

depends on https://github.com/Haulmont/jmix-security/issues/94

**Comment by karandashovrz** [comment]
QA notes:
menus permissions are responsible for MenuItem and SubMenuItem disaplaying. If user doesn't have permission for current MenuItem or SubMenuItem then they are not be displayed. Mapping with menus permissions and MenuItem/SubMenuItem works by "key" property of MenuItem/SubMenuItem.

screens permissions are responsible for screen content disaplaying (in tab or bradcrumb). If user doesn't have permission for current screen then its content is not be displayed and user will see text "You don't have access to this screen" (depends with locale). Mapping with screens permissions and screens in application works by "screenId".

If screens or menus permissions has item with target equal *, it means that user has permissions for all menu items or screens.

Permission checking for menus and screens could be off. It works by REACT_APP_ENABLE_UI_PERMISSIONS env variable. By default REACT_APP_ENABLE_UI_PERMISSIONS equal false and checking is off. If you need to enable checking just set value of REACT_APP_ENABLE_UI_PERMISSIONS to true
