### ISSUE TITLE
Screen path has not been cleaned after close the last tab

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-frontend#404]
**Enviroment:
Jmix version: 1.0**.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT3036-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Ultimate Edition)

**TC:**
1. Create frontend module 
2. Add new frontend component entity manageent for User - > Finish
3. Run app -> open browser
4. Open User browser -> close tab

**AR:**
path has not been cleared
![image](https://user-images.githubusercontent.com/45730069/122003335-01a7f280-cdc4-11eb-9edc-aa20c2947e6a.png)

**ER:**
path has been cleared

**Comment by vyacheslav-pushkin** [comment]
Routing is not changed when closing any tab, not only last tab.

**Comment by abarinovhaulmont** [comment]
Also url doesn't change when we click on tabs and change them. I fixed this issue too in this PR.
