### ISSUE TITLE
Add confirm windows for master-detail

### ISSUE THREAD

**Issue by HegelPro** [Haulmont/jmix-frontend#408]
First, need to close this [issue](https://github.com/Haulmont/jmix-frontend/issues/373)

When we select a new entity for editing or unselect the old entity needs to show confirm window.

QA:

template:
`master-detail`

If you have touched the form and have tried to select a new entity, the confirm window must appear.

**Comment by owlet1997** [comment]
**TC:**
1. Create master-details screen for any entity -> Run app
2. Open the entity master-details screen -> Select any entity in DataTable
**AR:**
entity is opened for editing in a form
![image](https://user-images.githubusercontent.com/45730069/135084601-8a34f916-8eb0-4ef4-b4cf-87ec1b562e1d.png)

3. Change anything in the editor 
![image](https://user-images.githubusercontent.com/45730069/135084648-1454ce88-0a4c-40f8-98f6-bf7140a5c8e7.png)

and unselect the edited entity in DataTable

**AR:**
the form is hided
![image](https://user-images.githubusercontent.com/45730069/135084677-1acdf347-a781-451b-b902-f6807a35fb1f.png)

4. Click again to the edited entity in DataTable

**AR:**
confirm window is displayed
![image](https://user-images.githubusercontent.com/45730069/135084738-bf1daee3-c4a9-42f7-8184-87d90b2f0852.png)

**ER:**
it's not clear why the form is hided in this case
> or **unselect the old entity** needs to show confirm window.
so may be user should see the confirm window after unselecting the entity
