### ISSUE TITLE
Mocking server fails to start (subscription related)

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-frontend#411]
Enviroment:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3071-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Ultimate Edition)

TC:
1. Open attached project
2. Open NewEntityEdit.tsx -> select mode Editor and preview
3. Click `Start React UI Preview Dev Server`
4. Select checkbox `Backend mode`

AR:
![image](https://user-images.githubusercontent.com/45730069/122337636-a6a30680-cf4f-11eb-9ae4-1eef7849647b.png)

ER:
server has been started successfully

[backmockmod.zip](https://github.com/Haulmont/jmix-frontend/files/6667653/backmockmod.zip)

**Comment by web-devel** [comment]
Bug in studio https://youtrack.jmix.io/issue/JST-1547

Use plugin 1.0 to avoid
