### ISSUE TITLE
Fix render DOM elements inside Screen's TabPanel component

### ISSUE THREAD

**Issue by HegelPro** [Haulmont/jmix-frontend#415]
1. Inside inside Screen's TabPanel component render extra 3 divs and span elements. (could be helpful in e2e tests)
![17 06](https://user-images.githubusercontent.com/34520941/122374983-e11e9a80-cf73-11eb-9285-34f5d3c6cc94.png)

2. Remove the invalid character `/` in TabPanel's id attribute.
![17 06 2](https://user-images.githubusercontent.com/34520941/122374991-e24fc780-cf73-11eb-9790-4b426be795d7.png)

**Comment by vyacheslav-pushkin** [comment]
Regarding point 1: it seems to be on antd side and have already been fixed since:

![image.png](https://images.zenhubusercontent.com/5d8878ed64a0e5000151de39/e1c180c0-4892-45b5-9a86-7a65283e213f)__

**Comment by vyacheslav-pushkin** [comment]
Regarding point 2: according HTML5 standard `/` [is a valid character for id value](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute).
