### ISSUE TITLE
Register screens in palette.tsx

### ISSUE THREAD

**Issue by web-devel** [Haulmont/jmix-frontend#460]
The idea is that screen can also be dropped as other components

**Comment by lovtsovaik** [comment]
@SvyatovetsD please provide more information about the issue and how to test it

**Comment by SvyatovetsD** [comment]
@lovtsovaik
Generated screen should be available in `React Components` section of Jmix Studio plugin under `Screens` category, so you can drag'n'drop it the same way as any other component. 

1. Generate new screen in Jmix Studio
2. Newly generated screen should appear in `React Components` section under `Screens` category
