### ISSUE TITLE
Wrong component's preview displaying after registering HomePage.tsx 

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-frontend#495]
**Enviroment:**
Jmix version: 1.0.0
Jmix Studio plugin version: 1.1.SNAPSHOT3212-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Ultimate Edition)

**TC:**
1. Create new project
2. Add frontend module
3. Create frontend component Entity management for User entity
4. Add to previews.tsx 
```
<ComponentPreview path="/">
    <HomePage />
</ComponentPreview>
```
5. Open UserEditor.tsx -> Start React preview dev server -> create graphql scheme and start Backend dev mode

**AR:**
Homepage component preview is displayed
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/6e3a4e20-4349-42af-892f-8e2ba4401718)

UPD: in new project content from HomePage.tsx is displayed with other component's content:
![image](https://user-images.githubusercontent.com/45730069/124717041-ceb1d400-df15-11eb-9a70-603d2ec71ec0.png)

**ER:**
User editor component preview is displayed

**Comment by HegelPro** [comment]
In general, it works correctly, almost like in `react-router` library. The difference with `react-router` is that we render by path prop more than the first Route(all with path collisions).
If we have collisions in paths and one of the route paths should be exactly like a current path in the studio. We need to write exactly route this way with exact props:
```
<ComponentPreview path="/" exact>
    <HomePage />
</ComponentPreview>
```

**Comment by HegelPro** [comment]
In npm package `@haulmont/react-ide-toolbox`  version `1.0.1 and upper` exact prop will be true by default.
