### ISSUE TITLE
DataTools addon

### ISSUE THREAD

**Issue by karandashovrz** [Haulmont/jmix-frontend#512]
Addon package name `@haulmont/jmix-addon-data-tools`
Installing:
```
npm i @haulmont/jmix-addon-data-tools
gen-jmix-front react-typescript:addon --dest src --addonPackageName @haulmont/jmix-addon-data-tools --model ./generation/projectModel.json
```
Version tracker: https://www.npmjs.com/package/@haulmont/jmix-addon-data-tools

**Comment by owlet1997** [comment]
**TC:**
1. Create any instances of entity with Soft delete trait
2. Open Entity Inspector screen -> Select the entity in the combobox
3. Delete any instance

**AR:**
deleted instance is not displayed in the table

**ER:**
deleted instance should be displayed

**Comment by owlet1997** [comment]
**TC 2:**
1. Create any instances of entity with Soft delete trait
2. Open Entity Inspector screen -> Select the entity in the combobox
3. Select deleted entity -> Edit

**AR:**
fields are empty:
![image](https://user-images.githubusercontent.com/45730069/143419710-f709882c-a80f-4346-b43b-585ab0a912ec.png)

**ER:**
entity attributes are displayed in the fields

**Comment by owlet1997** [comment]
**TC 3:**

1. Create any instances of entity with Soft delete trait
2. Open Entity Inspector screen -> Select the entity in the combobox
3. Select deleted entity -> Remove -> Confirm

**AR:**
unhandled exception:
![image](https://user-images.githubusercontent.com/45730069/143420366-a9d173c2-1472-4bfb-bec5-58ba72e484db.png)

**ER:**
should be discussed

**Comment by owlet1997** [comment]
**TC 4:**

1. Open Entity Inspector screen -> Select the entity in the combobox
2. Create 11 instances of the entity
3. Open second page
4. Select entity -> Remove -> Confirm
**AR:** the first page is opened
5. Scroll down

**AR:**
pagination block has two buttons:
![image](https://user-images.githubusercontent.com/45730069/143422298-34b75e13-4b12-4f27-a779-17fc94b57f16.png)

after clicking button `2` nothing is happened

**ER:**
one button `1` should be displayed

**Comment by owlet1997** [comment]
TC 5:
 entity with Versioned trait is used

1. Open Entity Inspector screen -> Select the entity in the combobox
2. Create new

**AR:**
field `Version` is displayed and required so user is not able to create new instance without setting a version

**ER:**
displaying of this field has no sense because this attribute is autogenerated

**Comment by owlet1997** [comment]
**TC 5:** 

1. Create user without permission to restore entities -> Login
2. Open entity inspector -> Select the entity with Soft delete trait
3. Select any deleted entity in the table -> Restore

**AR:**
unhandled exception:
![image](https://user-images.githubusercontent.com/45730069/143425341-2795a155-c7e2-4d5c-9c20-e8b5c1f97217.png)
 
**ER:**
user should see a notification about lack of access
