### ISSUE TITLE
i18n: parameterization

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#551]
#### Test coverage requirements

Spec requires at least 10 tests (in Frontend).

i18n snippets: https://github.com/jmix-projects/front-demo-r2/blob/main/frontend/src/app/i18n/ParametrizedMessages.tsx

**Comment by web-devel** [comment]
Please provide tests in frontend also

**Comment by karandashovrz** [comment]
Tests for parametrization: https://github.com/Haulmont/jmix-frontend/blob/master/packages/jmix-react-web/src/i18n/LocalesStore.ts
