### ISSUE TITLE
Tooling support: frequently used actions

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#553]
### Background

Currently, Studio includes visual designers and wizards for creating a project, screens and other basic elements of the application. Thanks to them, a developer can quickly (and without writing any code) create a skeleton of a real software system.

However, after the developer moves on to implement more specific requirements of their project, they quickly come to the need to write code - even for typical actions. This can be avoided by providing a **library of typical actions**. Studio will provide developers with instrumental support for generating the necessary code and setting the parameters of operations.

### What needs to be done

Basically a "typical action" is a code snippet template that can be interpolated into resulting code by providing necessary parameters.

- Provide a contract for adding new typical actions in application or addon. Studio will scan the project and addons and allow using typical actions defined there.
- Write code snippets for typical actions (see list below) and include them in a way detectable by Studio (existing runtime libs? separate lib using addon contract?).

### List of supported typical actions

**According to specification** we need to support at least the following typical actions:

- Screens
  - Open screen `(Screen API invocation, parameter - ReactComponent representing the screen)`
  - Close current screen `(Screen API)`
  - Open dialog `(Ant modal, parameters - ReactComponent, title, etc.)`
- Data and forms
  - Validate form fields `(context: Form.Item)`
  - Save entity changes `(create mutation + useMutation hook)`
  - Save screen changes `(similar to above, but multiple entities / instances)`
  - Load entities using GraphQL query: one, optional one, a list `(create query + useQuery/useLazyQuery hook, const items = ...)`
- UI
  - Open confirmation modal
  - Open a link `(URL navigation)`
  - Localized message `(imperative API: useIntl, intl.formattedMessage(...), + key/value to all json OR choose existing key. Context: React component.)`
  - Show notification `(Ant notification, parameters - i18n key)`
- Server communication
  - Invoke Spring MVC service `(axios REST API invocation, parameters - endpoint, method GET/PUT/POST, context path, parameters can be literals or variables from current context)`

### Supported parameter types

- Screen identifier (`React Component name`)
- String message
- i18n message key
- Current screen component
- A variable of a certain type available in the current context

### Test coverage requirements

Specification requires at least 10 tests.

**Comment by karandashovrz** [comment]
Action snippets: https://github.com/Haulmont/jmix-frontend/tree/actions/example-react-app/src/actions

**Comment by vyacheslav-pushkin** [comment]
@ilya-trifonov  

1. Copy the snippets from https://github.com/jmix-projects/front-demo-r2/tree/main/frontend/src/app/tools/user-actions to this project (into example-react-app as custom file)
2. Write 10 units tests (add to example-react-app as custom file)

**Comment by ilya-trifonov** [comment]
### QA Notes

tests:
`test-pup/example-react-app/user-actions.test.js`
