### ISSUE TITLE
Implement approach to theming

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#556]
See #13 for the list of requirements.

**Comment by karandashovrz** [comment]
For QA: Application's themes presets is located in `frontend/src/hemes/antd-themes` (see image below)

![image.png](https://images.zenhubusercontent.com/60000377f9c3e0334cc6b83d/699f1477-99ef-45f1-8183-61058beb7c63)

By default, application has two themes presets: light and dark. Theme file is less file with set of less variables, which override ​​initialized antd values. For adding new theme preset, need to do next:
1) Add less file with set of variables  to `frontend/src/hemes/antd-themes`  directory
2) Add theme preset info into `themes` property of `themes.config.json` (location:  `frontend/src/themes/themes.config.json`)
![image.png](https://images.zenhubusercontent.com/60000377f9c3e0334cc6b83d/6d44dedb-e573-423f-8528-394daca1b9a0)
`name` property must match with preset file name (like `dark` or `light`), `caption` property is intl key which used for theme preset name in UI ThemeSwitcher component (in ui, this component si located in header, near with language switcher).

After that in runed application, new theme preset will be avalible for switching.

Also, exists feature of size's presets. For adding size preset need to do next:
1) Add less file with set of sizes variables to `frontend/src/hemes/antd-themes/sizes`  directory (if `sizes` directory not exist, need to create it)
2) Add size preset info into `sizes` property of `themes.config.json`.  (location:  `frontend/src/themes/themes.config.json`). It's like adding `theme` preset. `name` property must match with size preset file name. `caption` property is intl key which used for size name preset in UI ThemeSwitcher component.

To understand, how current less variable could be change application layout, look at this resource:  https://antdtheme.com

**Comment by owlet1997** [comment]
Environment:
Jmix version: 1.0.999-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3552-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)

Checked:
- [ ] new theme creating
- [ ] new size creating
- [ ] switching between themes
- [ ] switching between sizes
