### ISSUE TITLE
Url in the address bar should reflect only root screen

### ISSUE THREAD

**Issue by SvyatovetsD** [Haulmont/jmix-frontend#587]
Since it's not clear at the moment how to reflect screen api state in the address bar it's better to update url with the root url of the opened screen

For example:
Opened "Car List" tab -> /carList
Opened "Car Form" in the Car List screen -> /carList

**Comment by vyacheslav-pushkin** [comment]
@SvyatovetsD Please rewrite the ticket title/description as it doesn't reflect the approach we decided to take.
