### ISSUE TITLE
Document title should be updated in align with the page content

### ISSUE THREAD

**Issue by SvyatovetsD** [Haulmont/jmix-frontend#590]
Steps:
1. Navigate across the generated app
2. Open recent browser history

Actual
All the pages have the same name that is the name of the app

Expected
It should be possible to differentiate the pages

**Comment by owlet1997** [comment]
**Environment:**
Jmix version: 1.0.999-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3552-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)
generator version: 1.1.0-next.2

**TC:**
1. Navigate across the app
2. Open recent browser history and remember the time of visiting:
![image](https://user-images.githubusercontent.com/45730069/134923471-0288eaa9-e51b-4038-ad02-785fe7bbd011.png)
3. Wait a minute and navigate again
4. Refresh recent browser history page

**AR:**
time of entries was refreshed, new visit's entries were not added:
![image](https://user-images.githubusercontent.com/45730069/134923685-97badf41-1a05-44ba-b382-e5277a24b5b2.png)
