### ISSUE TITLE
Some interfaces of @apollo/client in last major version are incompatibility with interfaces in current version

### ISSUE THREAD

**Issue by karandashovrz** [Haulmont/jmix-frontend#609]
Some interfaces of @apollo/client in last major version (3.5.x) are incompatibility with interfaces in current version, which used in packages (3.3.15).  As temporary fix, version 3.3.15 was declared as static version in package.json files (in all packages). Need to update @apollo/client to last major version and fix issues with interfaces incompatibility (in all packages).

**Comment by vyacheslav-pushkin** [comment]
3.5.x is currently in beta
