### ISSUE TITLE
Frontend crashes when entity contains FileRef attribute on entity form

### ISSUE THREAD

**Issue by SvyatovetsD** [Haulmont/jmix-frontend#614]
![image](https://user-images.githubusercontent.com/31245557/132310180-578815d4-6a28-4232-8344-113af151e145.png)

## QA Notes

Needs to be tested in versions 2.0.0-next.x and 1.1.0. 
1.1.0 will be published once the ticket is tested in 2.0.0-next.x.
@owlet1997

**Comment by vyacheslav-pushkin** [comment]
For now we should ignore such attributes

**Comment by vyacheslav-pushkin** [comment]
There is now backend support for files.

**Comment by owlet1997** [comment]
Describe please which permissions user should has to have access to upload/download files

**Comment by owlet1997** [comment]
**Environment:**
Jmix version: 1.1.0
Jmix Studio plugin version: 1.1.SNAPSHOT3695-212
IntelliJ version: IntelliJ IDEA 2021.2.3 (Ultimate Edition)

**AR**:
unable to upload/download any file using frontend editor:
![image](https://user-images.githubusercontent.com/45730069/139647959-87d6ee63-d745-4394-bab3-817fbe8104ce.png)
![image](https://user-images.githubusercontent.com/45730069/139647986-51f48ff0-72c1-4f67-8477-9e8ee18dc542.png)
Test project 
[fr110.zip](https://github.com/Haulmont/jmix-frontend/files/7451977/fr110.zip)
