### ISSUE TITLE
[Components: Complex] EntityPicker

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#635]
Allows selecting an entity instance Typically associated with a referenced attribute of a data source entity.

Port EntityLookupField from Amplicode and wrap it in FieldPermissionContainer / Form.Item.

e2e tests required.

**Comment by owlet1997** [comment]
**TC:**
1. Create an entity with association with another entity
2. Create an editor for the entity
3.  Use the EntityPickerField component

**AR:**
component is not displayed:
![image](https://user-images.githubusercontent.com/45730069/144057316-40f0ccbc-0ff0-4493-8e91-0a52832327e9.png)
