### ISSUE TITLE
Missing dependencies in generated app's package.json

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-frontend#641]
**Environment:**
Jmix version: 1.0.999-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3539-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)
OS: Ubuntu 20.04 LTS

**TC:**
1. Create new project 
2. Add frontend module -> set the latest frontend generator version `1.1.0-next.2`
3. Create any frontend component for User entity

**AR:**
components were generated with incorrect imports:
editor:
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/d9508e2b-19c2-4563-89e5-b0d56d76e916)
cards:
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/39e72f67-5901-4352-8b27-cb3733beb463)
list:
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/b96e918e-29d8-433b-befb-dc09480b7186)

**Comment by vyacheslav-pushkin** [comment]
@owlet1997 These imports are correct, you are probably adding components to an app generated with an older version of the generator.

**Comment by owlet1997** [comment]
@vyacheslav-pushkin here is a version from package.json:
![photo_2021-09-23_09-01-53](https://user-images.githubusercontent.com/45730069/134456835-545b9ad0-b182-424c-a5bf-3ffb169ca29d.jpg)

**Comment by vyacheslav-pushkin** [comment]
@owlet1997 could you please post the `dependencies` part of `package.json` in generated project (not the generator itself)?

**Comment by owlet1997** [comment]
```
"dependencies": {
    "@ant-design/icons": "^4.6.2",
    "@apollo/client": "^3.4.0",
    "@haulmont/jmix-react-core": "^1.0.0",
    "@haulmont/jmix-rest": "^1.0.0",
    "@haulmont/react-scripts": "^1.0.0",
    "@haulmont/react-ide-toolbox": "^1.0.0",
    "antd": "^4.13.0",
    "graphql": "^15.4.0",
    "mobx": "^6.3.3",
    "mobx-react": "^7.2.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-input-mask": "^2.0.4",
    "react-intl": "^5.3.0",
    "react-router-dom": "^5.2.0"
  }
```

**Comment by vyacheslav-pushkin** [comment]
@owlet1997 Thanks, it's a valid bug in generator

**Comment by vyacheslav-pushkin** [comment]
@owlet1997 A workaround to be able to test other tickets is to do `npm i @haulmont/jmix-react-web @haulmont/jmix-react-antd`

**Comment by owlet1997** [comment]
> @owlet1997 A workaround to be able to test other tickets is to do `npm i @haulmont/jmix-react-web @haulmont/jmix-react-antd`

I tried to use your workaround and had another installation error:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: jfr@undefined
npm ERR! Found: @apollo/client@3.4.13
npm ERR! node_modules/@apollo/client
npm ERR!   @apollo/client@"^3.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @apollo/client@"3.3.15" from @haulmont/jmix-react-web@1.0.0-next.1
npm ERR! node_modules/@haulmont/jmix-react-web
npm ERR!   @haulmont/jmix-react-web@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/shatalova/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shatalova/.npm/_logs/2021-09-23T09_23_54_405Z-debug.log
```

**Comment by vyacheslav-pushkin** [comment]
@owlet1997 We'll fix that. In the meantime this should work:

```
npm i @haulmont/jmix-react-web @haulmont/jmix-react-antd --legacy-peer-deps
```

**Comment by owlet1997** [comment]
@vyacheslav-pushkin Another import is highlighted as error:
![photo_2021-09-23_13-56-33](https://user-images.githubusercontent.com/45730069/134488246-b6175988-49b6-4d5c-9b8a-65bfb6b6d68a.jpg)
As a result after starting app there is a compilation error

**Comment by vyacheslav-pushkin** [comment]
@owlet1997 Please try:

```
npm i @haulmont/jmix-react-web@1.0.0-next.2 @haulmont/jmix-react-antd@1.0.0-next.2
 --legacy-peer-deps
```

**Comment by owlet1997** [comment]
Frontend generator v.1.1.0-next.5 was checked
