### ISSUE TITLE
[Components: Containers] App Layout: Header, Footer, Sidebar

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#692]
Components that allow setting up application layout without using CSS. 

Usage example:

```jsx
<AppLayout>
  <Header> { /* components that should be displayed in header */ } </Header>
  <AppLayout>
    <Sidebar> { /* ... in sidebar */ } </Sidebar>
    <Content> { /* ... in content */ } </Content> 
  </AppLayout>
  <Footer> { /* ... in footer */ } </Footer>
</AppLayout>
```

e2e tests required.

### QA Notes
`import { AppLayout, Header, Sidebar, Footer, Content } from "@haulmont/jmix-react-antd";`

Test: `test-pup/example-react-app/layouts.test.ts`

Components AppLayout, Header, Sidebar, Footer, Content are just simple wrappers around antd [Layouts](https://ant.design/components/layout/)

**Comment by owlet1997** [comment]
rename Sider component to Sidebar
