### ISSUE TITLE
[Components: Data Display] EntityHierachyTree

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#696]
Implement functionality similar to [this component](https://demo.jmix.io/sampler/#main/0/sample?id=tree-simple).

`<EntityHierachyTree>` will receive an entity instances collection and `hiearachyProperty` prop which determines which of the entity's properties is the link to parent entity instance.

For example, if we have three entity instances:

```
const items = [{
  id: '1',
  _instanceName: 'Instance A',
  parent: undefined,
},
{
  id: '2',
  _instanceName: 'Instance B',
  parent: '1'
},
{
  id' 3',
  _instanceName: 'Instance C',
  parent: '2'
}]
```

then using the component like this:

```
<EntityHierarchyTree items={items}
                                   hierarchyProperty='parent'
/>
```

will render:

```
Instance A
├─ Instance B
     ├─ Instance C
```

Use Ant Design [Tree](https://ant.design/components/tree/) as tree component implementation.

e2e tests required.

#### QA Notes
`import { EntityHierachyTree } from "@haulmont/jmix-react-antd";`

Tests: [EntityHierarchyTree](https://github.com/Haulmont/jmix-frontend/blob/master/test-pup/example-react-app/entity-hierarchy-tree.test.js)

**Comment by vyacheslav-pushkin** [comment]
@deanex Please add e2e tests location to QA Notes

**Comment by owlet1997** [comment]
**TC:**
set 'parent' value `undefined`
**AR:**
compilation error:
![image](https://user-images.githubusercontent.com/45730069/144373764-2972612b-d306-450b-958d-6e19a19f5a7f.png)
