### ISSUE TITLE
[Components: Data Display] ProgressBar

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#699]
Visualization of task progress.

e2e tests required.

**Comment by ilya-trifonov** [comment]
#### QA Notes
`import {ProgressBar} from @haulmont/react-antd;`

Must have prop `percent`

example:
`<ProgressBar percent={50} />`

e2e test:
`test-pup/example-react-app/progress-bar.test.js`
