### ISSUE TITLE
[Components: Controls] SelectField

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#705]
Allows selection of one or several items from the drop-down list. Allows you to type the item name in order to filter the available data (including requesting from the server).

Use Ant Design `Select`.

e2e tests required.

**Comment by ilya-trifonov** [comment]
import {SelectField} from @haulmont/react-antd;
Use in place of <Field>

test-pup/example-react-app/form-controls/select-field.test.js
