### ISSUE TITLE
[Components: Controls] Button

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#708]
Should be covered by e2e tests

**Comment by vyacheslav-pushkin** [comment]
@ilya-trifonov QA Notes

**Comment by ilya-trifonov** [comment]
#### QA Notes
`import {Button} from @haulmont/react-antd;`

example:
`<Button type="primary" htmlType="submit">Button text</Button>`

e2e test:
`test-pup/example-react-app/form-controls/button.test.js`
