### ISSUE TITLE
[Components: Controls] Slider

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#709]
Displays and selects a range of values ​​using draggable sliders.

Use Ant Design `Slider`.

Should be covered by e2e tests.

**Comment by ilya-trifonov** [comment]
#### QA Notes
`import {SliderField} from @haulmont/react-antd;`
Use in place of `<Field>`

**Comment by ilya-trifonov** [comment]
path to test:
`test-pup/example-react-app/form-controls/slider-field.test.js`
