### ISSUE TITLE
[Components: Controls] FileUpload

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#712]
- [ ] Create `FileUploadField` component (wrap our existing component `FileUpload`)
- [ ] Write e2e tests for `FileUploadField`

**Comment by ilya-trifonov** [comment]
#### QA Notes
`import {FileUploadField} from @haulmont/react-antd;`
Use in place of `<Field>`

e2e test:
`test-pup/example-react-app/form-controls/file-upload-field.test.js`
