### ISSUE TITLE
[Components: Controls] MaskedField

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#713]
Allows a masked input (`Field` renders it for UUID fields, can be seen in `DataTypesTestEntity` screen).

Use our component `InputWithMask` (also used by `Field`).

Should be covered by e2e tests

**Comment by ilya-trifonov** [comment]
#### QA Notes
`import {MaskedField} from @haulmont/react-antd;`

**Comment by ilya-trifonov** [comment]
path to test:
`test-pup/example-react-app/form-controls/masked-field.test.js`

**Comment by owlet1997** [comment]
**Comments:**
the element has the required prop `mask`
for UUID this mask is working:
`"99a99a99-a99a-99aa-aa9a-a9a99aa99a99"`
