### ISSUE TITLE
[Components: Controls] SourceCodeEditor

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#714]
Highlighted program code editor. Use existing implementation.

e2e tests required.

**Comment by ilya-trifonov** [comment]
#### QA Notes
`import {SourceCodeField} from @haulmont/react-antd;`
Use in place of `<Field>`

e2e test:
`test-pup/example-react-app/form-controls/source-code-editor.test.js`
