### ISSUE TITLE
[Components: Controls] RichTextArea

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#715]
Rich text WYSIWYG editor. 

Use existing third-party rich text editor implementation (Draft.js, React-Draft-WYSIWYG, Jodit-React, etc.)

e2e tests required.

**Comment by ilya-trifonov** [comment]
#### QA Notes
`import {RichTextArea} from @haulmont/react-antd;`
Use in place of `<Field>`

`test-pup/example-react-app/form-controls/rich-text-area-field.test.js`

**Comment by vyacheslav-pushkin** [comment]
@owlet1997 underlying implementation has been changed due to multiple issues, please fully re-test the functionality of the component

**Comment by vyacheslav-pushkin** [comment]
@owlet1997 i18n will be implemented under https://github.com/Haulmont/jmix-frontend/issues/861
