### ISSUE TITLE
[Components: Data Display] Table

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#718]
A table for displaying data. Being bound to a data source, it allows sorting, filtering, highlighting one or more rows. Has a filtering interface built into the header for each column corresponding to an attribute of the entity of the data model.

Component is implemented (`<DataTable>`), this ticket only requires writing e2e tests.

**Comment by vyacheslav-pushkin** [comment]
@ilya-trifonov QA Notes

**Comment by ilya-trifonov** [comment]
#### QA Notes
`import DataTable} from @haulmont/react-antd;`

Required props:
`loading`
`onFilterChange`
`onSortOrderChange`
`onPaginationChange`
`entityName`
`columnDefinitions`

simple example:
`<DataTable
                        loading={false}
                        onFilterChange={() => {}}
                        onSortOrderChange={() => {}}
                        onPaginationChange={() => {}}
                        entityName={'scr_Car'}
                        columnDefinitions={[
                            'manufacturer',
                            'model'
                        ]}
                        items={[
                            {manufacturer: 'AAA', model: '001', id: '1'},
                            {manufacturer: 'BBB', model: '002', id: '2'},
                        ]}
                    />`

e2e test:
`test-pup/example-react-app/data-table.test.js`
