### ISSUE TITLE
No options on association to self entity

### ISSUE THREAD

**Issue by SvyatovetsD** [Haulmont/jmix-frontend#719]
When entity is referencing itself select has no options.

It should show all entities but one that is editing at the moment

**Comment by owlet1997** [comment]
**TC:**
1. Create entity with association 1-1 with itself 
2. Create Frontend component entity management for this entity
3. Start backend app 
4. Start frontend app
5. Create new instance of the entity
6. Create another one instance
7. Open association attribute combobox

**AR:**
list is empty:
![image](https://user-images.githubusercontent.com/45730069/140052650-73da6aab-75a7-4a8d-8975-c5807fc0f7ea.png)

after entity is saved and reopened for editing, list is not empty:
![image](https://user-images.githubusercontent.com/45730069/140052734-f8f769cc-9063-4f09-b92b-7fc46a5c1ca4.png)

**Comment by owlet1997** [comment]
**TC 2:**
1. Create entity with association 1-1 with itself 
2. Create Frontend component entity management for this entity
3. Select attribute with association in GraphQL constructor -> Finish editing

**AR:**
extra query was added to EntityList:
![image](https://user-images.githubusercontent.com/45730069/140053504-4c112445-8243-4452-b6d8-57f4800148e2.png)

**Comment by vyacheslav-pushkin** [comment]
@owlet1997 

https://github.com/Haulmont/jmix-frontend/issues/719#issuecomment-958949133 - this is Studio issue
