### ISSUE TITLE
Less invasive addon mechanism

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#739]
- [x] Jmix
- [x] Amplicode
- [ ] Docs

**Comment by karandashovrz** [comment]
For QA:
Mechanism of addons injection became less invasive. When you inject addon in application by generator, import of addon will added to **src/addons.ts** file. If addon has own palette component, it will added to main palette file **src/dev/palette.tsx**. There will be no other changes in the code. This mechanism work the same in jmix and amplicode.

**Comment by owlet1997** [comment]
Checked:

- [ ] Jmix
- [ ] Amplicode
