### ISSUE TITLE
Client-side bean validation

### ISSUE THREAD

**Issue by web-devel** [Haulmont/jmix-frontend#744]
### UPDATE

Now studio passes bean validation rules to project model. We need to propagate it to metadata.json and implement client-side validation for the following rules:

```
          "beanValidationRules": [
            {
              "name": "Email"
            },
            {
              "name": "Email"
              "regexp": ".*"
            },
            {
              "name": "DecimalMax",
              "value": "12.78"
            },
            {
              "name": "DecimalMin",
              "value": "12"
            },
            {
              "name": "Digits",
              "integer": 1,
              "fraction": 1
            },
            {
              "name": "Future"
            },
            {
              "name": "FutureOrPresent"
            },
            {
              "name": "Max",
              "value": 123
            },
            {
              "name": "Min",
              "value": 123
            },
            {
              "name": "Negative"
            },
            {
              "name": "NegativeOrZero"
            },
            {
              "name": "NotBlank"
            },
            {
              "name": "NotEmpty"
            },
            {
              "name": "NotNull"
            },
            {
              "name": "Past"
            },
            {
              "name": "PastOrPresent"
            },
            {
              "name": "Pattern",
              "regexp": ".*"
            },
            {
              "name": "Positive"
            },
            {
              "name": "PositiveOrZero"
            },
            {
              "name": "Size"
            }
          ]
```

------------------

### Summary

Currently Bean Validation constraints are only validated server-side. We need to implement client-side validation for:

- Not null (mandatory)
- Length
- Size
- Pattern
- Email

Information about these constraints will be included to `projectModel`: [Studio ticket](https://youtrack.jmix.io/issue/JST-2259).

### What needs to be done

- Propagate bean validation rules to metadata.json.
- Apply bean validation on the client side implicitly in <Field/> component.
- Provide API to check validation for specific entity attribute value.

### Notes

Regarding `Pattern`: note that Java regexp are not interchangeable with JavaScript regexp below ES2018 (look-behind is only available in JavaScript regexp starting from ES2018 + ignore case is different).

**Comment by owlet1997** [comment]
Project for testing - 
[front1.zip](https://github.com/Haulmont/jmix-frontend/files/7659034/front1.zip)

**Comment by owlet1997** [comment]
**TC 1:**
1. Open the project -> Run the app
2. Open Str Size Entity List -> Create new
3. Set "1234" to the Str size attr -> Submit
**AR:** validation has been worked successfully
4. Set "123456" to the Str size attr -> Submit

**AR:**
the same validation has been working for the Name field without any reason
![image](https://user-images.githubusercontent.com/45730069/144810326-82fe067b-a4b7-4cc3-8ade-10484195d365.png)

**Comment by owlet1997** [comment]
**TC 2:**

1. Open the project -> Run the app
2. Open Str Length Entity List -> Create new
3. Set "12" to the Str size attr -> Submit

**AR:**
 nothing has happened, the error occurs in the console:
![image](https://user-images.githubusercontent.com/45730069/144810636-12221f43-e5e5-4a89-8c10-f09be437c071.png)

**Comment by owlet1997** [comment]
Test project
[front.zip](https://github.com/Haulmont/jmix-frontend/files/7659823/front.zip)

**Comment by owlet1997** [comment]
**TC 3:** 

1. Open the project -> Run the app
2. Open Pattern Entity List -> Create new
3. Set "dogggg" to the Email attr -> Submit

**AR:**
the entity has not been saved because of validation:
![image](https://user-images.githubusercontent.com/45730069/144827480-449e8420-0ee7-472a-8472-c59113fabe2b.png)
