### ISSUE TITLE
Template mechanism extension - Entity attribute - add attribute type

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#781]
Possible attribute types:

- "number",
- "string",
- "boolean",
- "reference",
- "datetime",
- "date",
- "time"
 
Metadata will contain acceptable types for given field.

Example:

```
{
  "code": "startDate",
  "caption": "Event start date",
  "propertyType": "ATTRIBUTE",
  "options": [
    "datetime",
    "date",
  ]
}
```

**Comment by HegelPro** [comment]
if we don't insert options, it means that a property of `ATTRIBUTE` type can be any type.
