### ISSUE TITLE
Pagination buttons aren't working after setting any params to URL

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-frontend#783]
**Environment:**
Jmix version: 1.1.0
Jmix Studio plugin version: 1.1.SNAPSHOT3792-212
IntelliJ version: IntelliJ IDEA 2021.2.3 (Ultimate Edition)
generator version: 2.0.0-next.6

**Shared steps:**
1. Clone [the project](https://github.com/jmix-projects/front-demo-r2) -> Run app
2. Open Localhost:3000 -> Login as admin
3. Open Templates -> Entity Management
4. Append to URL `?page=1&pageSize=2` -> Press Enter

**TC 1:**
5. Try to go to another page using pagination buttons

**AR:**
nothing happened, first page is still displayed

**TC 2:**
6. Select in the `per page` drop-down any params 

**AR:**
URL params weren't changed:
![image](https://user-images.githubusercontent.com/45730069/142878250-af0f3974-0a88-4251-9807-8d4c2b86b5de.png)

**Comment by SvyatovetsD** [comment]
Looks like the screen was generated with old version of generator. Newly generated screens work as expected.

**Comment by owlet1997** [comment]
can not reproduce
