### ISSUE TITLE
Rename CUBA to Jmix in error message

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-frontend#804]
Now: `Error: Can't establish connection to CUBA Studio. Please open CUBA Studio Intellij and tick 'Enable Integration' checkbox.`

Must be: `Error: Can't establish connection to Jmix Studio. Please open Jmix plugin settings in IntelliJ IDEA and select 'Enable integration' checkbox.`

### QA Notes

To reproduce, try creating a frontend module with 'Enable integration' checkbox switched off.

This should be tested on version 0.9 and 3.0.0.

**Comment by lovtsovaik** [comment]
@00unnmd please add QA notes: how to reproduce this error

**Comment by owlet1997** [comment]
**Environment:**
Jmix version: 1.2.0-SNAPSHOT
Jmix Studio plugin version: 1.2.SNAPSHOT4011-213
IntelliJ version: IntelliJ IDEA 2021.3.2 Preview (Ultimate Edition)
Frontend generator version: 0.9.0, 0.9.1-sb.3

**AR:**
CUBA name is still used in the error message:
![image](https://user-images.githubusercontent.com/45730069/150531581-f2c0d313-a8a3-43b8-9a72-f9395363bdf2.png)

**Comment by vyacheslav-pushkin** [comment]
@ilya-trifonov Please port the fix to `release_0_9` branch.
