### ISSUE TITLE
[Accessibility] Keyboard navigation is problematic

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#805]
> karandashovrz commented 43 minutes ago

> For completly accessibility support, need to check and fix some issues with tab key navigation:

> 1. Navigation inside Tab item. Navigation with tab key inside Tab item works incorrectly. User can't navigate to close Tab button and activate it from keybord.
> 1. Navigation inside Table component. At now, user can't navigate to table component and navigate inside table component with tab key from keybord (to rows, to column header, to column header buttons as sorting and filtering)
> 1. Navigation to breadcrumbs. At now, user can't navigate to breadcrumbs and activate any breadcrumb.
> 1. Navigation to Structure template items. At now, user can't navigate to Structure template items with tab key. This leads to screen readers not voicing content inside items.
> 1. Navigation to Grid template items. Look 4 point, same issues.
> 1. Navigation to With Details template items. Look 4 point, same issues.

### QA Notes
Table navigation cannot be completed due to antd library Table component restrictions

**Comment by karandashovrz** [comment]
For completly accessibility support, need to check and fix some issues with tab key navigation:
1) Navigation inside Tab item. Navigation with tab key inside Tab item works incorrectly. User can't navigate to close Tab button and activate it from keybord.
2) Navigation inside Table component. At now, user can't navigate to table component and navigate inside table component with tab key from keybord (to rows, to column header, to column header buttons as sorting and filtering)
3) Navigation to breadcrumbs. At now, user can't navigate to breadcrumbs and activate any breadcrumb.
4) Navigation to Structure template items. At now, user can't navigate to Structure template items with tab key. This leads to screen readers not voicing content inside items.
5) Navigation to Grid template items. Look 4 point, same issues.
6) Navigation to With Details template items. Look 4 point, same issues.

**Comment by vyacheslav-pushkin** [comment]
@deanex Point 2 sounds like it might be (partially?) caused by Ant Design `Table` component. The scope of this ticket only covers our own code.
