### ISSUE TITLE
Composition field is not disabled by `disabled` property on `field`

### ISSUE THREAD

**Issue by andreysubbotin** [Haulmont/jmix-frontend#814]
- Create an editor component for an entity with composition
- Try to disable the composition field `disabled` property, like:
```
<Field
            entityName={ENTITY_NAME}
            propertyName="menuPolicies"
            formItemProps={{
              style: { marginBottom: "12px" }
            }}
            disabled={item?.readOnly === true}
          />
```
AR: Field is not disabled. You can able to create/remove items in the composition table
ER: You can able to navigate to the composition table. Create/delete/edit actions should be disabled.

**Comment by owlet1997** [comment]
**TC 1:** One to One Composition entity
field code:
```
 <Field
            entityName={ENTITY_NAME}
            propertyName="child"
            disabled={true}
            formItemProps={{
              style: { marginBottom: "12px" }
            }}
          />
```
**AR:**
user is not able to navigate to the composition entity
![image](https://user-images.githubusercontent.com/45730069/144974303-45c9e6d3-6521-4aeb-8580-02c4a67183c0.png)

**Comment by owlet1997** [comment]
**TC 2:** One to Many Composition entity
field code:
```
 <Field
            entityName={ENTITY_NAME}
            propertyName="childs"
            disabled={true}
            formItemProps={{
              style: { marginBottom: "12px" }
            }}
          />
```
**AR:**
user is able to navigate to the composition table but Create/delete/edit actions are not disabled:
![image](https://user-images.githubusercontent.com/45730069/144974643-42f43f96-fce8-4989-bd52-11ec0ae7c034.png)
![image](https://user-images.githubusercontent.com/45730069/144974684-249e6623-8421-4fdb-a2b0-ce29b876cd26.png)

**Comment by vyacheslav-pushkin** [comment]
@owlet1997 Were Pattern Entity List and the editor for O2O composition generated with latest version of frontend generator?

**Comment by owlet1997** [comment]
@vyacheslav-pushkin you were right, I used the screens were generated by an older version of the generator
