### ISSUE TITLE
Unable to add frontend module

### ISSUE THREAD

**Issue by Vorobey31415** [Haulmont/jmix-frontend#822]
IntelliJ IDEA 2021.3 (Ultimate Edition)
Build #IU-213.5744.223, built on November 27, 2021
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Jmix version 1.1.0
npm -v
7.21.1
node -v
v14.17.5

Error while npm install (package.json in attachments):
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --scripts-prepend-node-path=auto
npm WARN ancient lockfile 
npm WARN ancient lockfile The package-lock.json file was created with an old version of npm,
npm WARN ancient lockfile so supplemental metadata must be fetched from the registry.
npm WARN ancient lockfile 
npm WARN ancient lockfile This is a one-time fix-up, please be patient...
npm WARN ancient lockfile 
npm WARN ERESOLVE overriding peer dependency
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: react-intl@5.23.0
npm ERR! Found: typescript@4.4.4
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^4.5" from @formatjs/intl@1.17.0
npm ERR!   node_modules/react-intl/node_modules/@formatjs/intl
npm ERR!     @formatjs/intl@"1.17.0" from react-intl@5.23.0
npm ERR!     node_modules/react-intl
npm ERR!       react-intl@"^5.3.0" from the root project
npm ERR!       1 more (@haulmont/jmix-react-ui)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional typescript@"^4.5" from react-intl@5.23.0
npm ERR! node_modules/react-intl
npm ERR!   react-intl@"^5.3.0" from the root project
npm ERR!   peer react-intl@"^5.3.0" from @haulmont/jmix-react-ui@1.1.1
npm ERR!   node_modules/@haulmont/jmix-react-ui
npm ERR!     @haulmont/jmix-react-ui@"^1.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: typescript@4.5.2
npm ERR! node_modules/typescript
npm ERR!   peerOptional typescript@"^4.5" from react-intl@5.23.0
npm ERR!   node_modules/react-intl
npm ERR!     react-intl@"^5.3.0" from the root project
npm ERR!     peer react-intl@"^5.3.0" from @haulmont/jmix-react-ui@1.1.1
npm ERR!     node_modules/@haulmont/jmix-react-ui
npm ERR!       @haulmont/jmix-react-ui@"^1.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/vorobevaa/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vorobevaa/.npm/_logs/2021-12-02T06_27_52_136Z-debug.log

Process finished with exit code
[package.zip](https://github.com/Haulmont/jmix-frontend/files/7639540/package.zip)
 1

**Comment by vyacheslav-pushkin** [comment]
Fixed in 2.0.0-next.10
