### ISSUE TITLE
Several issues with data-tools addon

### ISSUE THREAD

**Issue by karandashovrz** [Haulmont/jmix-frontend#825]
Several bugs were found after QA testing. Bugs was described in comments inside [this ticket](https://app.zenhub.com/workspaces/platform-frontend-5fe0992a4308f20011f1c913/issues/haulmont/jmix-frontend/512) by @owlet1997

**Comment by owlet1997** [comment]
Issues check-list:

- [ ] displaying a deleted instance
- [ ] editing a deleted instance
- [ ] removing a deleted entity
- [ ] displaying the Version field in the editor
- [ ] restoring a deleted entity without permission

**Comment by owlet1997** [comment]
**TC:**
1. Open Entity Inspector -> Select an entity with Soft Delete Trait
2. Remove an entity
2. Edit the removed entity -> Save

**AR:**
the entity is not removed anymore:
![image](https://user-images.githubusercontent.com/45730069/144627546-9f137bfd-7bb9-4d8f-b1dd-7455c7b244fe.png)

**Comment by owlet1997** [comment]
the separated [ticket](https://github.com/Haulmont/jmix-frontend/issues/838) was created for the last test case
