### ISSUE TITLE
"Module not found: Can't resolve 'draft-js'" when using npm 6

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-frontend#846]
**Environment:**
IntelliJ IDEA 2021.3 RC (Ultimate Edition)
Build #IU-213.5744.125, built on November 17, 2021
Runtime version: 11.0.13+7-b1751.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2014M
Cores: 8
Non-Bundled Plugins:
    com.intellij.lang.jsgraphql (3.0.0)
    io.jmix.studio (1.2.SNAPSHOT3878-213)
Kotlin: 213-1.5.10-release-949-IJ5744.125

**TC:**
1. Create a new project using the 1.1.1 Jmix version
2. Add a frontend module using 2.0.0-next.13 generator version
3. Create a new frontend component Entity management for the User entity
4. Run the Jmix app -> Run the React Frontend app

**AR:**
Failed to compile.
```
./node_modules/@haulmont/jmix-react-antd/dist/index.esm.js
Module not found: Can't resolve 'draft-js' in 'C:\Users\shatalovanv\IdeaProjects\frontch\frontend\node_modules\@haulmont\jmix-react-antd\dist'
```

**Comment by vyacheslav-pushkin** [comment]
@ilya-trifonov peerDependencies from `jmix-react-antd` must be added to generated app dependencies, otherwise it won't work in npm6.

**Comment by vyacheslav-pushkin** [comment]
@ilya-trifonov To fix this move `draftjs`, `draftjs-to-html`, etc. from `peerDependencies` to `dependencies`. Only leave in `peerDependencies` the stuff that is already in the generated app ('mobx', 'react', etc.).

To elaborate: we don't want the user to manually install `draftjs`, etc. We want to bring them as transitive dependencies. 

npm 7+ will install `peerDependencies` automatically, but npm 6 won't.
