### ISSUE TITLE
Add i18n localization to RichTextEditor

### ISSUE THREAD

**Issue by ilya-trifonov** [Haulmont/jmix-frontend#861]

**Comment by owlet1997** [comment]
@ilya-trifonov please add QA notes

**Comment by ilya-trifonov** [comment]
#### QA Notes
editor should display english localization correctly in the heading type selector
should be: heading 1, heading 2, heading 3, heading 4 and normal

**Comment by ilya-trifonov** [comment]
@owlet1997 
I used this
        `<option value="1">{intl.formatMessage({id: 'jmix.richTextArea.headingOne'})}</option>`
        `<option value="2">{intl.formatMessage({id: 'jmix.richTextArea.headingTwo'})}</option>`
        `<option value="3">{intl.formatMessage({id: 'jmix.richTextArea.headingThree'})}</option>`
        `<option value="4">{intl.formatMessage({id: 'jmix.richTextArea.headingFour'})}</option>`
        `<option value="5">{intl.formatMessage({id: 'jmix.richTextArea.normalText'})}</option>`

instead this
        `<option value="1">Heading 1</option>`
        `<option value="2">Heading 2</option>`
        `<option value="3">Heading 3</option>`
        `<option value="4">Heading 4</option>`
        `<option value="5">Normal</option>`
