### ISSUE TITLE
Initial sort order doesn't work in table components

### ISSUE THREAD

**Issue by SvyatovetsD** [Haulmont/jmix-frontend#862]
### Steps to reproduce

1. Open CarBrowserTable.tsx editor
2. Set `defaultSortOrder` property of DataTable component to `{ manufacturer: 'ASC' }`
3. Open `http://localhost:3000/carBrowserTable`

### AR
Table shows unsorted items

### ER
Table shows items sorted by manufacturer in ascending order

**Comment by vyacheslav-pushkin** [comment]
@SvyatovetsD Please add the GraphQL request to the ticket: does it contain the sort order?
