### ISSUE TITLE
Charts addon: examples

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#877]

**Comment by owlet1997** [comment]
added screens:

**- Bar Chart Screen:**
- Bar Chart
- Clustered Bar Chart

**- Pie Chart Screen**
- Pie Chart
- Donut Chart

**- Line Chart Screen**
- Line Chart
- Smoothed Line Chart
- Stacked Line Chart

**- Funnel Chart Screen**
- Funnel Chart

**- RadialBar Chart Screen**
- RadialBar Chart

**- Radar Chart Screen**
- Radar Chart

**- Scatter Chart Screen**
- Scatter Chart

**- Waffle Chart Screen**
- Horizontal Waffle Chart
- Vertical Waffle Chart

**- Chord Chart Screen**
- Chord chart

**- Choropleth Chart Screen**
- Choropleth chart

**- Pivot Table Screen**
- Pivot chart
