### ISSUE TITLE
EntityPickerField should display selected entity instance name instead of ID

### ISSUE THREAD

**Issue by web-devel** [Haulmont/jmix-frontend#888]
![image](https://user-images.githubusercontent.com/3295727/147065207-1ce7b565-6a3d-40e0-a1dc-01ea6bc5d8ac.png)

ref #635

#### QA Notes
Entity Picker should show instance name after instance selection in Entity Picker on `/customFormControls` in example react app.

**Comment by vyacheslav-pushkin** [comment]
@vadimbasko Please add QA Notes
