### ISSUE TITLE
After invoking "Remove" action on any entity modal confirming window is not displayed

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-frontend#889]
**Environment:**
Jmix version: 1.2.0-SNAPSHOT
Jmix Studio plugin version: 1.2.SNAPSHOT3950-213
IntelliJ version: IntelliJ IDEA 2021.3 (Ultimate Edition)
OS Ubuntu 20.04

**TC 1:**
1. Clone the [project](https://github.com/jmix-projects/front-demo-r2)
2. Run the Jmix app -> Run the React frontend app -> Login as admin
3. Templates -> Entity Browser List 
4. Select any entity -> Click `Remove`
5. Templates -> Entity Browser Cards
6. Click `Remove` on any entity

**AR:**
the entity has been removed

**ER:** 
the modal confirming window is displayed

**TC 2:**
open Templates -> Entity Browser List -> try to remove any entity

**AR:**
nothing happened, the modal confirming window is not displayed and the entity has not been removed

**Comment by HegelPro** [comment]
The reason is that browser templates were generated with the old version of the generator. If you regenerate browser templates all will work correctly.
I going to update browser templates in the [project](https://github.com/jmix-projects/front-demo-r2)
