### ISSUE TITLE
Cannot add O2M Composition item

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [Haulmont/jmix-frontend#900]
#### TC

1. Open entity list for an entity that has a O2M Composition attribute
2. Click `Create`
3. Find O2M Composition attribute and click `+ Add entities`
4. Click `Create`
5. Populate the editor fields
6. Click `OK`

#### AR

Nothing happens

#### ER

Child editor closed, create item added to child entity list

**Comment by HegelPro** [comment]
The ticket's problem appears inside `@haulmont/jmix-addon-user-management` addon's screens.

If we generate editors in our application O2M Composition attributes works correctly.

**Comment by HegelPro** [comment]
fixed with updating frontend model in [front-demo-r2](https://github.com/jmix-projects/front-demo-r2)

**Comment by owlet1997** [comment]
**TC:**
1. Open the attached project -> Run app
2. Sales -> Product List -> Create any product
3. Sales -> Order List
4. Create a new instance -> try to add an OrderLine

**AR:**
![image](https://user-images.githubusercontent.com/45730069/148738861-7560e3ea-e709-4f40-bfaf-3a3de1fcbf4e.png)

[frontdemo.zip](https://github.com/Haulmont/jmix-frontend/files/7837634/frontdemo.zip)
